[{"bug_type":"RESOURCE_LEAK","qualifier":"resource of type `java.io.FileOutputStream` acquired to `fos` by call to `FileOutputStream(...)` at line 53 is not released after line 59.\n**Note**: potential exception at line 56","severity":"ERROR","line":59,"column":-1,"procedure":"Hello.twoResources():void","procedure_start_line":48,"file":"Hello.java","bug_trace":[{"level":0,"filename":"Hello.java","line_number":48,"column_number":-1,"description":"start of procedure twoResources()"},{"level":0,"filename":"Hello.java","line_number":49,"column_number":-1,"description":""},{"level":0,"filename":"Hello.java","line_number":50,"column_number":-1,"description":""},{"level":0,"filename":"Hello.java","line_number":52,"column_number":-1,"description":""},{"level":0,"filename":"Hello.java","line_number":53,"column_number":-1,"description":""},{"level":0,"filename":"Hello.java","line_number":54,"column_number":-1,"description":""},{"level":0,"filename":"Hello.java","line_number":56,"column_number":-1,"description":"Taking true branch"},{"level":0,"filename":"Hello.java","line_number":56,"column_number":-1,"description":"exception java.io.IOException"},{"level":0,"filename":"Hello.java","line_number":59,"column_number":-1,"description":""}],"key":"Hello.java|twoResources|RESOURCE_LEAK","node_key":"48815eab4c26cee962db00712b67bbd0","hash":"0c8093eee70747f011b0cac872db7161","bug_type_hum":"Resource Leak"}]
